// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoComex.Data;

#nullable disable

namespace ProyectoComex.Migrations
{
    [DbContext(typeof(ComexContext))]
    [Migration("20250703122307_CuitAsUniqueField")]
    partial class CuitAsUniqueField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoComex.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("CUIT")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CUIT")
                        .IsUnique();

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CUIT = "20345678901",
                            Direccion = "Av. Mitre 1234",
                            RazonSocial = "Ferretería San José",
                            Telefono = "1123456789"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CUIT = "27345678902",
                            Direccion = "Calle Falsa 123",
                            RazonSocial = "Distribuidora El Sol",
                            Telefono = "1134567890"
                        },
                        new
                        {
                            Id = 3,
                            Activo = false,
                            CUIT = "30765432109",
                            Direccion = "San Martín 456",
                            RazonSocial = "Panadería La Espiga",
                            Telefono = "1145678901"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
