// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoComex.Data;

#nullable disable

namespace ProyectoComex.Migrations
{
    [DbContext(typeof(ComexContext))]
    partial class ComexContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("ProyectoComex.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Activo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CUIT")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            CUIT = "20345678901",
                            Direccion = "Av. Mitre 1234",
                            RazonSocial = "Ferretería San José",
                            Telefono = "1123456789"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            CUIT = "27345678902",
                            Direccion = "Calle Falsa 123",
                            RazonSocial = "Distribuidora El Sol",
                            Telefono = "1134567890"
                        },
                        new
                        {
                            Id = 3,
                            Activo = false,
                            CUIT = "30765432109",
                            Direccion = "San Martín 456",
                            RazonSocial = "Panadería La Espiga",
                            Telefono = "1145678901"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
